name: TreasureCraftTakeaway
version: '${project.version}'
main: dev.r1nex.treasurecrafttakeaway.TreasureCraftTakeaway
softdepend: [ProtocolLib, DecentHolograms]
api-version: '1.16'
commands:
  treasure-takeaway:
    aliases: [tct]
